import React from 'react';
import { FaArrowLeft, FaShieldAlt, FaEnvelope } from 'react-icons/fa';
import { useNavigate } from 'react-router-dom';

const PrivacyPolicy = () => {
  const navigate = useNavigate();

  const handleBackPress = () => {
    navigate(-1);
  };

  return (
    <div className="min-h-screen bg-[#01035C]">
      {/* Content */}
      <div className="max-w-6xl mx-auto px-4 py-8">
        <div className="bg-[#02046B] rounded-xl shadow-lg border border-[#05067A] overflow-hidden">
          <div className="p-8 md:p-10">
            {/* Header Section */}
            <div className="text-center mb-10">
              <div className="inline-flex items-center justify-center w-20 h-20 bg-[#0A0B7A] rounded-full mb-5">
                <FaShieldAlt className="text-blue-300 text-3xl" />
              </div>
              <h1 className="text-white font-bold text-4xl mb-3">Privacy Policy</h1>
              <p className="text-blue-200">Last updated: June 02, 2025</p>
            </div>

            {/* Introduction */}
            <div>
              <p className="text-blue-100 leading-relaxed mb-7">
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </p>
              <p className="text-blue-100 leading-relaxed mb-7">
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>

              {/* Interpretation and Definitions */}
              <section className="mb-10">
                <h2 className="text-white font-bold text-3xl mb-5 flex items-center">
                  <span className="w-2 h-7 rounded bg-blue-400 mr-4"></span>
                  Interpretation and Definitions
                </h2>
                
                <h3 className="text-blue-200 font-semibold text-2xl mb-4">Interpretation</h3>
                <p className="text-blue-100 leading-relaxed mb-7">
                  The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>

                <h3 className="text-blue-200 font-semibold text-2xl mb-4">Definitions</h3>
                <p className="text-blue-100 leading-relaxed mb-5">For the purposes of this Privacy Policy:</p>
                <div className="space-y-4">
                  {[
                    { term: "Account", definition: "means a unique account created for You to access our Service or parts of our Service." },
                    { term: "Affiliate", definition: "means an entity that controls, is controlled by or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority." },
                    { term: "Application", definition: "refers to zeenoPay - Merchant Dashboard, the software program provided by the Company." },
                    { term: "Company", definition: "refers to Zeeno International Limited, 483 Green Lanes, London, United Kingdom." },
                    { term: "Country", definition: "refers to: United Kingdom" },
                    { term: "Device", definition: "means any device that can access the Service such as a computer, a cellphone or a digital tablet." },
                    { term: "Personal Data", definition: "is any information that relates to an identified or identifiable individual." },
                    { term: "Service", definition: "refers to the Application." },
                    { term: "Service Provider", definition: "means any natural or legal person who processes the data on behalf of the Company." },
                    { term: "Usage Data", definition: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself." },
                    { term: "You", definition: "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service." }
                  ].map((item, index) => (
                    <div key={index} className="bg-[#0A0B7A] p-5 rounded-xl border-l-4 border-blue-400">
                      <p className="text-blue-100">
                        <span className="font-semibold text-white">{item.term}:</span> {item.definition}
                      </p>
                    </div>
                  ))}
                </div>
              </section>

              {/* Data Collection */}
              <section className="mb-10">
                <h2 className="text-white font-bold text-3xl mb-5 flex items-center">
                  <span className="w-2 h-7 rounded bg-teal-400 mr-4"></span>
                  Collecting and Using Your Personal Data
                </h2>
                
                <h3 className="text-blue-200 font-semibold text-2xl mb-4">Types of Data Collected</h3>
                
                <h4 className="text-blue-200 font-medium text-xl mb-4">Personal Data</h4>
                <p className="text-blue-100 leading-relaxed mb-7">
                  While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                </p>
                <div className="bg-[#0A0B7A] p-5 rounded-xl mb-7">
                  {['Email address', 'First name and last name', 'Phone number', 'Address, State, Province, ZIP/Postal code, City', 'Usage Data'].map((item, index) => (
                    <div key={index} className="flex items-center text-blue-100 mb-3 last:mb-0">
                      <span className="w-2.5 h-2.5 rounded-full bg-blue-400 mr-4"></span>
                      {item}
                    </div>
                  ))}
                </div>

                <h4 className="text-blue-200 font-medium text-xl mb-4">Usage Data</h4>
                <p className="text-blue-100 leading-relaxed mb-7">
                  Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>

                <h4 className="text-blue-200 font-medium text-xl mb-4">Information Collected while Using the Application</h4>
                <p className="text-blue-100 leading-relaxed mb-7">
                  While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
                </p>
                <div className="bg-[#0A0B7A] p-5 rounded-xl mb-7">
                  {['Information regarding your location', 'Information from your Device\'s phone book (contacts list)', 'Pictures and other information from your Device\'s camera and photo library'].map((item, index) => (
                    <div key={index} className="flex items-center text-blue-100 mb-3 last:mb-0">
                      <span className="w-2.5 h-2.5 rounded-full bg-teal-400 mr-4"></span>
                      {item}
                    </div>
                  ))}
                </div>

                {/* Photo library access clarification */}
                <div className="bg-[#0A0B7A] p-5 rounded-xl mb-7 border border-blue-500">
                  <p className="text-blue-100 leading-relaxed">
                    <span className="font-semibold text-white">Photo Library Access:</span> We access your photo library only when you choose to upload an image to your profile or submit content. This access is solely for that purpose and we do not store your photo library contents. You can revoke this permission at any time through your device settings.
                  </p>
                </div>

                <p className="text-blue-100 leading-relaxed mb-7">
                  We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.
                </p>
                <p className="text-blue-100 leading-relaxed mb-7">
                  You can enable or disable access to this information at any time, through Your Device settings.
                </p>
              </section>

              {/* Data Usage */}
              <section className="mb-10">
                <h3 className="text-blue-200 font-semibold text-2xl mb-5">Use of Your Personal Data</h3>
                <p className="text-blue-100 leading-relaxed mb-5">The Company may use Personal Data for the following purposes:</p>
                <div className="grid gap-5 mb-10">
                  {[
                    { title: "To provide and maintain our Service", desc: "including to monitor the usage of our Service." },
                    { title: "To manage Your Account", desc: "to manage Your registration as a user of the Service." },
                    { title: "For the performance of a contract", desc: "the development, compliance and undertaking of the purchase contract." },
                    { title: "To contact You", desc: "by email, telephone calls, SMS, or other equivalent forms of electronic communication." },
                    { title: "To provide You with news and offers", desc: "special offers and general information about other goods and services." },
                    { title: "To manage Your requests", desc: "to attend and manage Your requests to Us." }
                  ].map((item, index) => (
                    <div key={index} className="bg-[#0A0B7A] p-5 rounded-xl border-l-4 border-teal-400">
                      <h4 className="font-semibold text-white mb-2 text-xl">{item.title}</h4>
                      <p className="text-blue-100">{item.desc}</p>
                    </div>
                  ))}
                </div>
              </section>

              {/* Data Security */}
              <section className="mb-10">
                <h2 className="text-white font-bold text-3xl mb-5 flex items-center">
                  <span className="w-2 h-7 rounded bg-red-400 mr-4"></span>
                  Security of Your Personal Data
                </h2>
                <div className="bg-[#0A0B7A] p-7 rounded-xl border border-red-400/30">
                  <p className="text-blue-100 leading-relaxed">
                    The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                  </p>
                </div>
              </section>

              {/* Children's Privacy */}
              <section className="mb-10">
                <h2 className="text-white font-bold text-3xl mb-5 flex items-center">
                  <span className="w-2 h-7 rounded bg-purple-400 mr-4"></span>
                  Children's Privacy
                </h2>
                <p className="text-blue-100 leading-relaxed mb-7">
                  Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
                </p>
              </section>

              {/* Contact Section */}
              <section className="bg-gradient-to-r from-[#0A0B7A] to-[#10128A] p-7 rounded-xl border border-blue-500/30">
                <h2 className="text-white font-bold text-3xl mb-5 flex items-center">
                  <FaEnvelope className="text-blue-300 mr-4" />
                  Contact Us
                </h2>
                <p className="text-blue-100 leading-relaxed mb-4">
                  If you have any questions about this Privacy Policy, You can contact us:
                </p>
                <a 
                  href="mailto:admin@zeenopay.com" 
                  className="flex items-center gap-3 text-blue-300 font-medium hover:underline text-lg"
                >
                  <FaEnvelope />
                  admin@zeenopay.com
                </a>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;