const countryCodes = [
  // Asia
  { mc: "+93", name: "Afghanistan", cc: "af" },
  { mc: "+374", name: "Armenia", cc: "am" },
  { mc: "+994", name: "Azerbaijan", cc: "az" },
  { mc: "+973", name: "Bahrain", cc: "bh" },
  { mc: "+880", name: "Bangladesh", cc: "bd" },
  { mc: "+673", name: "Brunei", cc: "bn" },
  { mc: "+86", name: "China", cc: "cn" },
  { mc: "+357", name: "Cyprus", cc: "cy" },
  { mc: "+91", name: "India", cc: "in" },
  { mc: "+62", name: "Indonesia", cc: "id" },
  { mc: "+98", name: "Iran", cc: "ir" },
  { mc: "+964", name: "Iraq", cc: "iq" },
  { mc: "+972", name: "Israel", cc: "il" },
  { mc: "+81", name: "Japan", cc: "jp" },
  { mc: "+962", name: "Jordan", cc: "jo" },
  { mc: "+7", name: "Kazakhstan", cc: "kz" },
  { mc: "+965", name: "Kuwait", cc: "kw" },
  { mc: "+996", name: "Kyrgyzstan", cc: "kg" },
  { mc: "+856", name: "Laos", cc: "la" },
  { mc: "+961", name: "Lebanon", cc: "lb" },
  { mc: "+960", name: "Maldives", cc: "mv" },
  { mc: "+976", name: "Mongolia", cc: "mn" },
  { mc: "+95", name: "Myanmar", cc: "mm" },
  { mc: "+977", name: "Nepal", cc: "np" },
  { mc: "+968", name: "Oman", cc: "om" },
  { mc: "+92", name: "Pakistan", cc: "pk" },
  { mc: "+63", name: "Philippines", cc: "ph" },
  { mc: "+974", name: "Qatar", cc: "qa" },
  { mc: "+82", name: "South Korea", cc: "kr" },
  { mc: "+94", name: "Sri Lanka", cc: "lk" },
  { mc: "+886", name: "Taiwan", cc: "tw" },
  { mc: "+66", name: "Thailand", cc: "th" },
  { mc: "+971", name: "United Arab Emirates", cc: "ae" },
  { mc: "+998", name: "Uzbekistan", cc: "uz" },
  { mc: "+84", name: "Vietnam", cc: "vn" },

  // Europe
  { mc: "+355", name: "Albania", cc: "al" },
  { mc: "+376", name: "Andorra", cc: "ad" },
  { mc: "+43", name: "Austria", cc: "at" },
  { mc: "+375", name: "Belarus", cc: "by" },
  { mc: "+32", name: "Belgium", cc: "be" },
  { mc: "+387", name: "Bosnia and Herzegovina", cc: "ba" },
  { mc: "+359", name: "Bulgaria", cc: "bg" },
  { mc: "+385", name: "Croatia", cc: "hr" },
  { mc: "+420", name: "Czech Republic", cc: "cz" },
  { mc: "+45", name: "Denmark", cc: "dk" },
  { mc: "+372", name: "Estonia", cc: "ee" },
  { mc: "+358", name: "Finland", cc: "fi" },
  { mc: "+33", name: "France", cc: "fr" },
  { mc: "+49", name: "Germany", cc: "de" },
  { mc: "+30", name: "Greece", cc: "gr" },
  { mc: "+36", name: "Hungary", cc: "hu" },
  { mc: "+354", name: "Iceland", cc: "is" },
  { mc: "+353", name: "Ireland", cc: "ie" },
  { mc: "+39", name: "Italy", cc: "it" },
  { mc: "+371", name: "Latvia", cc: "lv" },
  { mc: "+423", name: "Liechtenstein", cc: "li" },
  { mc: "+370", name: "Lithuania", cc: "lt" },
  { mc: "+352", name: "Luxembourg", cc: "lu" },
  { mc: "+373", name: "Moldova", cc: "md" },
  { mc: "+377", name: "Monaco", cc: "mc" },
  { mc: "+31", name: "Netherlands", cc: "nl" },
  { mc: "+47", name: "Norway", cc: "no" },
  { mc: "+48", name: "Poland", cc: "pl" },
  { mc: "+351", name: "Portugal", cc: "pt" },
  { mc: "+40", name: "Romania", cc: "ro" },
  { mc: "+7", name: "Russia", cc: "ru" },
  { mc: "+381", name: "Serbia", cc: "rs" },
  { mc: "+421", name: "Slovakia", cc: "sk" },
  { mc: "+386", name: "Slovenia", cc: "si" },
  { mc: "+34", name: "Spain", cc: "es" },
  { mc: "+46", name: "Sweden", cc: "se" },
  { mc: "+41", name: "Switzerland", cc: "ch" },
  { mc: "+44", name: "United Kingdom", cc: "gb" },
];

export default countryCodes;
